<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A3DO6K2" failures="1" tests="7" name="Test" time="0.099" errors="0" timestamp="2022-08-10T21:27:24 IST">
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="methodTwo" time="0.016"/>
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalyzer -->
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.003">
    <skipped/>
  </testcase> <!-- retryAnalyzer -->
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalyzer -->
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzer -->
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzer -->
  <testcase classname="Data.TestNG_Example.RetryAnalyzer" name="retryAnalyzer" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [123] but found [sree]">
      <![CDATA[java.lang.AssertionError: expected [123] but found [sree]
at Data.TestNG_Example.RetryAnalyzer.retryAnalyzer(RetryAnalyzer.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- retryAnalyzer -->
</testsuite> <!-- Test -->
